apiVersion: skaffold/v2beta29
kind: Config
metadata: 
  name: skaffold-deployment
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: ml_app
    context: components/ml_app
    docker:
      dockerfile: Dockerfile
    sync:
      infer:
      - '**/*'