apiVersion: skaffold/v2beta29
kind: Config
metadata: 
  name: skaffold-deployment
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: datadownloader
    context: components/datadownloader
    docker:
      dockerfile: Dockerfile
    sync:
      infer:
      - '**/*'
  - image: data_prep
    context: components/preprocessing
    docker:
      dockerfile: Dockerfile
    sync:
      infer:
      - '**/*'
  - image: model_train
    context: components/model-training
    docker:
      dockerfile: Dockerfile
    sync:
      infer:
      - '**/*'